steps:
 - name: 'gcr.io/kaniko-project/executor:latest'
   args:
    - --destination=$_GCR_ASIA_HOSTNAME/$PROJECT_ID/$_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:latest
    - --cache=true

 - name: 'gcr.io/cloud-builders/gcloud'
   entrypoint: /bin/bash
   args:
     - '-c'
     - |
         gcloud run deploy $_SERVICE_NAME --platform=managed --allow-unauthenticated  \
           --image=$_GCR_ASIA_HOSTNAME/$PROJECT_ID/$_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:latest \
           --region=$_REGION_HONGKONG \
           --set-env-vars=POD_ZONE=$_REGION_HONGKONG \
           --quiet
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _PLATFORM: managed
  _SERVICE_NAME: mpc
  _REPOSITORY: hjcore
  _REGION_HONGKONG: asia-east1
  _GCR_ASIA_HOSTNAME: asia-docker.pkg.dev
